In [10]:
# Q2
import numpy as np

np.random.seed(49)

A = np.random.randint(0, 10, size=(5, 5))
print("Matrix : A")
print(A)

Matrix : A
[[8 5 6 4 2]
 [5 5 1 2 4]
 [0 2 3 6 1]
 [6 4 8 3 8]
 [9 4 4 5 7]]


In [11]:
# Convert the matrix to row echelon form
def row_echelon_form(matrix):
    m = len(matrix)
    n = len(matrix[0])
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    break
        matrix[[i, r]] = matrix[[r, i]]
        if matrix[r, lead] != 0:
            matrix[r] = matrix[r] / matrix[r, lead]
        for i in range(m):
            if i != r:-
                matrix[i] = matrix[i] - matrix[i, lead] * matrix[r]
        lead += 1
    return matrix

# Get the row echelon form of matrix_A
row_echelon_A = row_echelon_form(A)
print("\nRow Echelon Form of Matrix A:")
print(row_echelon_A)



Row Echelon Form of Matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
