In [1]:
import numpy as np

np.random.seed(49)

A = np.random.randint(0, 10, size=(5, 5))
print("Matrix : A")
print(A)

Matrix : A
[[8 5 6 4 2]
 [5 5 1 2 4]
 [0 2 3 6 1]
 [6 4 8 3 8]
 [9 4 4 5 7]]


In [2]:
# Perform Singular Value Decomposition (SVD)
U, Sigma, VT = np.linalg.svd(A)
print("Matrix U:")
print(U)

print("Matrix Sigma:")
print(np.diag(Sigma))


print("Matrix V^T:")
print(VT)


Matrix U:
[[-0.25034994  0.32995395 -0.78176178  0.45016912 -0.12104375]
 [-0.59333573 -0.63993986 -0.25767711 -0.36256606 -0.20143993]
 [-0.26759758  0.66740283  0.07139887 -0.60427677 -0.33573322]
 [-0.29245431 -0.01838858  0.48482769  0.52114603 -0.63834259]
 [-0.6543238   0.18932166  0.28687164  0.1707338   0.65159213]]
Matrix Sigma:
[[2.42328002e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 7.31682211e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.49838976e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.71568400e-16
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  3.25987873e-16]]
Matrix V^T:
[[-5.04767930e-01 -4.89470893e-01 -4.74173857e-01 -4.58876821e-01
  -2.64988299e-01]
 [ 1.05493629e-01 -5.14490711e-02 -2.08391771e-01 -3.65334472e-01
   8.99626412e-01]
 [ 6.58847806e-01  2.40356481e-01 -1.78134845e-01 -5.96626170e-01
  -3.470641

In [3]:
reconstructed_A = U @ np.diag(Sigma) @ VT
print("Is A equal to the product of U, Sigma, and V^T?")
print(np.allclose(A, reconstructed_A))


Is A equal to the product of U, Sigma, and V^T?
True


In [4]:
# Rank 2 approximation of A
rank_2 = U[:, :2] @ np.diag(Sigma[:2]) @ VT[:2, :]
print("Rank 2 approximation of A:")
print(rank_2)
print()

# Rank 3 approximation of A
rank_3 = U[:, :3] @ np.diag(Sigma[:3]) @ VT[:3, :]
print("Rank 3 approximation of A:")
print(rank_3)


Rank 2 approximation of A:
[[ 3.31694977  2.84525423  2.37355868  1.90186314  3.77949022]
 [ 6.76369164  7.27860491  7.79351818  8.30843146 -0.40229319]
 [ 3.7883913   2.92280232  2.05721334  1.19162436  6.11147004]
 [ 3.56308987  3.47579599  3.38850211  3.30120823  1.75692744]
 [ 8.14978297  7.68982947  7.22987597  6.76992247  5.44787255]]

Rank 3 approximation of A:
[[1.00000000e+00 2.00000000e+00 3.00000000e+00 4.00000000e+00
  5.00000000e+00]
 [6.00000000e+00 7.00000000e+00 8.00000000e+00 9.00000000e+00
  1.73970435e-14]
 [4.00000000e+00 3.00000000e+00 2.00000000e+00 1.00000000e+00
  6.00000000e+00]
 [5.00000000e+00 4.00000000e+00 3.00000000e+00 2.00000000e+00
  1.00000000e+00]
 [9.00000000e+00 8.00000000e+00 7.00000000e+00 6.00000000e+00
  5.00000000e+00]]
