In [35]:
import numpy as np
import sympy as sp
np.random.seed(49)
A=np.random.randint(0,10,(5,5))
print(A)


[[8 5 6 4 2]
 [5 5 1 2 4]
 [0 2 3 6 1]
 [6 4 8 3 8]
 [9 4 4 5 7]]


In [36]:
A[0]=A[0]/8
A

array([[1, 0, 0, 0, 0],
       [5, 5, 1, 2, 4],
       [0, 2, 3, 6, 1],
       [6, 4, 8, 3, 8],
       [9, 4, 4, 5, 7]])

In [37]:
A[1]=A[1]-5*A[0]
A

array([[1, 0, 0, 0, 0],
       [0, 5, 1, 2, 4],
       [0, 2, 3, 6, 1],
       [6, 4, 8, 3, 8],
       [9, 4, 4, 5, 7]])

In [38]:
A[3]=A[3]-6*A[0]
A

array([[1, 0, 0, 0, 0],
       [0, 5, 1, 2, 4],
       [0, 2, 3, 6, 1],
       [0, 4, 8, 3, 8],
       [9, 4, 4, 5, 7]])

In [39]:
A[4]=A[4]-9*A[0]
A

array([[1, 0, 0, 0, 0],
       [0, 5, 1, 2, 4],
       [0, 2, 3, 6, 1],
       [0, 4, 8, 3, 8],
       [0, 4, 4, 5, 7]])

In [40]:
A[1]=A[1]/5
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 2, 3, 6, 1],
       [0, 4, 8, 3, 8],
       [0, 4, 4, 5, 7]])

In [41]:
A[2]=A[2]-2*A[1]
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 3, 6, 1],
       [0, 4, 8, 3, 8],
       [0, 4, 4, 5, 7]])

In [42]:
A[3]=A[3]-4*A[1]
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 3, 6, 1],
       [0, 0, 8, 3, 8],
       [0, 4, 4, 5, 7]])

In [43]:
A[4]=A[4]-4*A[1]
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 3, 6, 1],
       [0, 0, 8, 3, 8],
       [0, 0, 4, 5, 7]])

In [44]:
A[2]=A[2]/3
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 2, 0],
       [0, 0, 8, 3, 8],
       [0, 0, 4, 5, 7]])

In [45]:
A[3]=A[3]-8*A[2]
A

array([[  1,   0,   0,   0,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   2,   0],
       [  0,   0,   0, -13,   8],
       [  0,   0,   4,   5,   7]])

In [46]:
A[4]=A[4]-4*A[2]
A

array([[  1,   0,   0,   0,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   2,   0],
       [  0,   0,   0, -13,   8],
       [  0,   0,   0,  -3,   7]])

In [47]:
A[3]=A[3]/-13
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  1,  2,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0, -3,  7]])

In [48]:
A[2]=A[2]-2*A[3]
A

array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0, -3,  7]])

In [49]:
A[4]=A[4]+3*A[3]
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 7]])

In [50]:
A[4]=A[4]/7
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])